sudo: false
language: java
install:
- mvn -s .settings.xml install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script:
- mvn -s .settings.xml $MVN_GOAL -nsu -Dmaven.test.redirectTestOutputToFile=true
jdk:
- oraclejdk8
env:
  global:
  - FEATURE_BRANCH=$(echo ${TRAVIS_BRANCH} | grep "^.*/.*$" && echo true || echo false)
  - INTERNAL_BUILD=$(echo ${TRAVIS_REPO_SLUG} | grep -q "^SMARTRACTECHNOLOGY/.*$"
    && echo true || echo false)
  - MVN_GOAL=$([ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_TAG}" == "" -a "${FEATURE_BRANCH}"
    == "false" -a "${INTERNAL_BUILD}" == "true" ] && echo deploy || echo install)
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - secure: K7Ng2lS5PrGfn3THyT9it/U+/XA5RoFTHk6/lcLwNDAtgNGScaCzxPM2i6HXC6F1hxDyTqEZhSQBoHQcbFnBWYWeQfJug/xOv0GyKzPX9j+jxkcCWkicqFyvjgPBEWVf56Q6eQGO2S0OrWhWwZPTszOvl9LQqEn0cv/P0688jn28CjOjpoL7veZDOaOHkG7PNlVaAF8rkfMB5hz22HxaiScgrQYOCMdTrQ4VAbslYfaonJv2g4OLyIubJt/zxJSZ8/LOvFWYA3056KE8RDmY0RECRK4LTauXqQbxdBRHdlgfp+U8AmxiVuD8VRyTWY6ZCCFanHH53gUHJavrmi2wlkzonzPrDBEBOSqtHy/v6z7huopJRavkhPu5Vw+p80rv1UG8y06XDLSQOwewRj5MDTuyTidwwUPGYcznDbPCh20y/TfFqG2q1W+/hLWPVW1R4UBN6xSxUaonCS3/iWAxs74PdFlwuW1WqkZvE9+PV8FL7LY7nU/NOX/9l/KNgejHL2ScY2kQJqYeYLuGYAp2p6V1xTtdH8jMQVcvm7CrooNl7i+jNjUIFm2kpBOL5fu0nUyn1Bo7XgosMrLNU1QFRdXCt2KtSed9IIPPjtVIEAWLv4w/R2JwDFIZsu+9Lzqs/mZRLPkb7mmffHCIusTqe7BqbWHmnoUBWg098K3lNMA=
  - secure: Gtz2C0WAjbCBNELnJ7ozMAIhj1gcWstJg7uZKaQkRaHq6WkcwyO+onKMGxHuawp+zRquyLzymEXz/TUfGfGbb3xyB/ytAGCHbwFW6VRl8rlMdU3D03XEnxDEtxiJir/i95QMySibYgLka9Qs1z7Ihb4xsHh7TOr3uEPzmg9xcoYwPnnALwmEmldglEt4cks2IszczBZCiZ5QrqCU3CCdtJ6W8qF08QkaXqKdHkC0N80xv+YGkTjgx2o+SKE7UY21NQRnhN4RswiHm1YfP1Z5rHsvOC6jA3VeNu8wCANxPt0VNsp0XMwgY5oPV4IqEoPITcr2NfWJoXkHvsoiiI91P6dOPtY2Ru4sFcKZ6S4ONilaFAJ+EDlcwuyHmYivkUAmCSdzSMFMsgkuqvkUkb6W+s9UFMSQORSmdY3oz3QMMlsUpEIDu/ELWI9r0hufNXorLiwLZvTNi59jQMt4OCBQmfcHRN5dBXeIeZPSzu1jXEycAew86gMkGg4KDGIbjaGediVe/NY85p8AXYnEcriW/uCTcqF0Xb8cV/UFAwAusOXVcFi38P4bGtho06jf3AG5/rTm9UMk4gYVuE+khPqBhcGlSVKDM+uExAp3qpHot3lBTsFgtNq4M2ErvK5MuyVj3lS2J73JxTXFpF/1NZDhS1tRVvgpNzvrvnWSebjrH+Y=
notifications:
  slack:
    on_success: change
    rooms:
      secure: BtG5oc1YUPCkdOtjoPR9zFXK9KQMh8rVK99u6BOyiNJXGgCT/v5Pl2mXdcUBuGgpINos7C5pbD/yNAmKufipYcdQWD9CnJ0faCbYMzkX/isD5i6XP8nBFRkP1hDj5cwBXbp2n6jdr8J/aVZWBRDyYgrvkj5G0yzOET3iLDpyOBDAfjyRcmWSBJhV3q7IEZvr16NePXXPxH3GITWOyVuTaNPqDSAp5GuD+5D4lR1wrlwQXqJTCoJAIepcAia7vEYCIKQyCtLVPhUOPlchGDI1vJ/+pc4qq+OBR/tTWm+/TfUwJUpFQNY54ZekIWJyu9vX4eZOJBOO4u+WciDKa7q1CvHh1FXnAcLENcwnJWGzP9kAnSZiMDy6BSbytdwscI+MEccsulNnWXP364EmzLOr73Z4JonUrhN6pC/cx5oPX85GDlShhabNI06FVkjzNNyUOf62r8vWUV07mZjhC/dw4J4Xxcg0Z7pT8YBafHjUngAoIK/hprxtYdIzVEs+icsjKhXlGSOt4gwXFTUw4erpoOKJLfBs9fZHYosW/VqDsxByJ341U36aMsXp1mHmbNjgp00ey1AJWLGigh5Y4A0iiUP2+x76CsGo4vQFWVN5MA1DFBLkMwrUQsQUmM37ovSUyAIH9uXeaxPL4iwkcPHncScpRL9c7FsxqyBu7MBzUgA=
